pipeline {

    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        timeout(time: 15, unit: 'MINUTES')
    }

    tools {
        nodejs 'node24'
    }

    triggers {
        pollSCM('H/5 * * * *')
    }

    stages{

        stage('Run API Tests') {
            agent {
                docker { image 'node:24-alpine' }
            }
            steps {
                sh 'npm install newman'
                sh 'npx newman run tests/postman/Tests-for-Automation.postman_collection.json --reporters cli,junit --reporter-junit-export resultados.xml  '
            }
        }

    }

    post {
        always {
            junit 'resultados.xml'
        }
    }
}