pipeline {

    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        timeout(time: 15, unit: 'MINUTES')
    }

    tools {
        nodejs 'node24'
    }

    triggers {
        pollSCM('H/5 * * * *')
    }

    stages{

        stage('Checkout') {
            steps {
                git branch: 'main', 'url': "https://github.com/ssgeorocks/EventsApp_Express_JS.git"
            }
        }

        stage('Run API Tests') {
            steps {
                sh 'newman run tests/postman/collection.json --reporters cli,junit --reporter-junit-export resultados.xml  '
            }
        }

    }

    post {
        always {
            junit 'resultados.xml'
        }
    }
}